# Generated by Django 3.2.16 on 2022-12-31 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20221231_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='reply_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='reply_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
