# Generated by Django 3.2.16 on 2023-01-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221231_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='accepted_answer',
            field=models.BooleanField(default=False),
        ),
    ]
