version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/api
    working_dir: /api
    command: python3 manage.py runserver 0.0.0.0:8080
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - 5432:5432
